"""Add column signature,page to the model

Revision ID: 762d1358d6a3
Revises: 1f7d5d0ff95b
Create Date: 2024-07-18 09:53:55.996753

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "762d1358d6a3"
down_revision: Union[str, None] = "1f7d5d0ff95b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "song",
        sa.Column("signature", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column("song", sa.Column("page", sa.Integer(), nullable=True))
    op.alter_column(
        "songbook", "description", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "songbook", "description", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("song", "page")
    op.drop_column("song", "signature")
    # ### end Alembic commands ###
