---
name: Pre Commit
on:
  pull_request:
  merge_group:
    types: [checks_requested]
  workflow_dispatch:

jobs:
  pre-commit:
    name: Pre Commit Hooks
    runs-on: ubuntu-latest
    container: quay.io/fedora/fedora-minimal:latest
    steps:
    - name: Install requirements
      run: microdnf install -y git tar python3-pip
    - uses: actions/checkout@v4
    - name: Install pre-commit
      run: pip install pre-commit
    - name: State to use Workspace Dir
      run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
    - name: Run pre-commit on entire codebase
      run: pre-commit run --show-diff-on-failure --color=always --all-files
